[tool.setuptools]
[tool.setuptools_scm]

[build-system]
requires = ["setuptools>=75.6", "setuptools-scm>=8.1"]
build-backend = "setuptools.build_meta"

[project]
name = "ics_caldav_sync"
dynamic = ["version"]
requires-python = ">=3.9"
authors = [{name = "Przemysław Buczkowski", email = "prem@prem.moe"}]
description = "ICS to CalDAV synchronisation."
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Office/Business :: Scheduling",
    "Topic :: Internet",
]
readme = "README.md"

dependencies = [
    "arrow==1.3.0",
    "attrs==24.2.0",
    "caldav==1.4.0",
    "certifi==2024.8.30",
    "charset-normalizer==3.4.0",
    "click==8.1.7",
    "icalendar==6.1.0",
    "ics==0.8.0.dev0",  # a pre-release with added support for timezones
    "ics_vtimezones==2020.2",
    "idna==3.10",
    "importlib_resources==6.4.5",
    "lxml==5.3.0",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.2",
    "recurring-ical-events==3.3.4",
    "requests==2.32.3",
    "six==1.17.0",
    "types-python-dateutil==2.9.0.20241206",
    "tzdata==2024.2",
    "urllib3==2.2.3",
    "vobject==0.9.8",
    "x-wr-timezone==2.0.0",
]

[project.scripts]
ics_caldav_sync = "ics_caldav_sync:main"

[project.urls]
Repository = "https://github.com/przemub/ics_caldav_sync"
